name: FE Dev EC2
on:
  workflow_dispatch:
  push:
    tags:
    - v.*-dev-ec2

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1

        - name: Setup Node environment
          uses: actions/setup-node@v2
          with:
            node-version: 20

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Download .env.development from S3
          run: |
            aws s3 cp s3://gachagalaxy-envs/frontend/.env.development ./.env.development

        - name: copy build to remote
          uses: burnett01/rsync-deployments@5.1
          with:
            switches: -avzr --delete
            path: ./
            remote_path: ${{ secrets.DEV_PATH }}
            remote_host: ${{ secrets.DEV_HOST_DNS }}
            remote_user: ${{ secrets.DEV_USERNAME }}
            remote_key: ${{ secrets.DEV_EC2_SSH_KEY }}

        - name: executing remote ssh commands
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEV_HOST_DNS }}
            username: ${{ secrets.DEV_USERNAME }}
            key: ${{ secrets.DEV_EC2_SSH_KEY }}
            script: |
                cd ${{ secrets.DEV_PATH }}
                npm install
                pm2 delete gacha-fe
                pm2 start /home/ubuntu/projects/run.sh --name gacha-fe --time
                pm2 save
